import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'ko_KR': {
      'Sign Out': '로그아웃',
      'Sign in': '로그인',
      'Sign In': '로그인',
      'SIGN IN': '로그인',
      'Home': '홈',
      'Map': '지도',
      'Message': '메시지',
      'User': '사용자',
      'User Info': '사용자 정보',
      'Ranking Top 10': '친구 랭킹 Top 10',
      'Rank': '랭킹',
      'ID': '아이디',
      'User ID': '아이디',
      'Days': '일',
      'days': '일',
      'Streak': '연속',
      'Distance': '거리',
      'Close': '확인',
      'Cancel': '취소',
      'Confirm': '확인',
      'NO': '아니요',
      'YES': '예',
      'Ranking All Users': '모든 사용자 랭킹',


      'Send Message': '메시지 보내기',
      'Do you want to send message to your friend?': '친구에게 메시지를 보네시겠습니까?',


      // 로그인 관련 내용
      'Please sign in': '로그인 해주세요',
      'No friends in the list': '등록된 친구가 없습니다',
      'No Message': '메시지가 없습니다',
      'Please enter your username & password to sign in': '아이디와 비밀번호를 입력해 주세요',
      'Password': '비밀번호',
      'Password confirm': '비밀번호 재확인',
      'Enter Password again to confirm': '비밀번호를 다시 입력해 주세요',
      'Succeed to reset password': '비밀번호 재설정이 완료되었습니다',
      'Reset Password': '비밀번호 재설정',
      'Please enter your new password': '새로운 비밀번호를 입력해 주세요',
      'Password not valid': '비밀번호 오류',
      'Auto sign in': '자동 로그인',
      'Password not matched': '비밀번호가 일치하지 않습니다',
      'Please check your password and try again': '비밀번호를 다시 확인해 주세요',
      'User ID not valid': '아이디가 존재 하지 않습니다',
      'Please check your user ID and try again': '아이디를 다시 확인해 주세요',
      'Registration completed successfully': '회원 등록 성공',
      'Thank you for your registration': '회원 등록 감사합니다.',
      'Error occurred': '오류 발생',
      'Please try again a moment later': '다시 시도해 주시기 바랍니다',
      'Forgot Password?': '비밀번호 분실',
      'Create account': '회원 가입',
      'Enter User Information': '사용자 정보 입력',
      '* required': '* 필수입력',
      'Gender': '성별',
      'Male': '남성',
      'Female': '여성',
      'Username': '이름',
      'Email': '이메일',
      'Email not matched': '이메일이 일치하지 않습니다',
      'Please check your email and try again': '이메일을 다시 확인해 주세요',
      'Invalid email': '이메일 형식 오류',
      'Enter your name (or nickname)': '이름 입력',
      'Too short': '길이가 짧아요',
      'Enter new user ID': '새로운 아이디 입력',
      'Check ID': '아이디 중복확인',
      'ID - Existed': '아이디 사용불가',
      'It is being used by another user already. Please try different user ID.'
          : '아이디가 이미 사용중입니다. 다른 아이디를 사용해 주세요',
      'Enter Password (> 6 characters)': '비밀번호 입력 (6자리 이상)',
      'Please check the followings': '다음 사항(들)을 다시 확인해 주세요',
      'Privacy Policy': '개인정보처리방침',
      'Terms of Use': '이용약관',
      'Service Agreement': '이용 동의',
      'Agree all the terms and conditions': '모든 이용약관 동의',
      'Terms of use agreement (required)': '이용약광항목(필수)',
      'Privacy policy agreement (required)': '개인정보보호(필수)',
      'Please agree all the terms and conditions to proceed next step'
          : '다음 진행을 위해서 모든항목에 대한 동의가 필요합니다',
      'Next': '다음',
      'agreement_subtitle': '보다 원할한 서비스 이용 및 사용자의 데이터를 보다 안전하게 '
          '관리하기 위해서 아래의 약관 동의 및 회원 가입이 필요합니다.',

      'year': '년',
      'Year': '',
      'month': '월',
      'Mon': '월',
      'Tue': '화',
      'Wed': '수',
      'Thu': '목',
      'Fri': '금',
      'Sat': '토',
      'Sun': '일',
      'All': '전체',
      'Jan': '1월',
      'Feb': '2월',
      'Mar': '3월',
      'MAR': '3월',
      'Apr': '4월',
      'May': '5월',
      'Jun': '6월',
      'JUN': '6월',
      'Jul': '7월',
      'Aug': '8월',
      'Sep': '9월',
      'SEP': '9월',
      'Oct': '10월',
      'Nov': '11월',
      'Dec': '12월',
      'DEC': '12월',
      '30': '30일',
    },
    'en_US': {
      'agreement_subtitle': 'To store and manage your personal information safely, '
          'it is required to agree the terms below and sign up.',
    }
  };
}